# Generated by Django 5.0.6 on 2024-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOUTIQUE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boutique_images/'),
        ),
    ]
