# Generated by Django 5.0.6 on 2024-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOUTIQUE', '0005_rename_created_at_order_order_date_remove_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
